### ISSUE TITLE
Not Receiving Weather Alert Notification

### ISSUE THREAD

**Issue by Photo64** [custom-components/weatheralerts#28]
**Version of the custom_component**
Installed: 61049c6

**Describe the bug**
I currently have a production setup and a Dev setup running. My production setup is using this community add-on and my Dev setup is using the setup from here -> https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853

I believe both of these are capturing alerts from the the U.S. National Weather Service however this component doesn't seem to return any alerts. I did receive an alert from the other service in my Dev environment. I did not receive an alert from this component. This is what is showing for this sensor:

![image](https://user-images.githubusercontent.com/18359302/71782828-7d392980-2fac-11ea-85c6-3ec59a61a5ea.png)

Here is what is showing for my Dev setup:
![image](https://user-images.githubusercontent.com/18359302/71782851-c25d5b80-2fac-11ea-83cc-558aca1c7bc9.png)

I was expecting to receive the same alert for this component. Maybe I have something setup incorrectly however I believe it is setup correctly but it never seems to return any alerts. I am not seeing any errors in the logs for this component so I am unable to provide that. Please advise if I have something incorrectly setup that would prevent me from receiving the alerts. I would like to use this component due to its simplicity and use through HACS.

This is my currently yaml setup:
```
- platform: weatheralerts
  state: NJ
  zone: 10
```

**Log**
Not seeing any errors int the logs
```

**Comment by ludeeus** [comment]
From that post you should be using `https://api.weather.gov/alerts/active?zone=NJZ010` which returns the same as this integration.

**Comment by Photo64** [comment]
So my understanding is that I install your component through HACS, which I have done, and then add 
```
- platform: weatheralerts
  state: NJ
  zone: 10
```
to my sensor yaml, which I have also done however no alert is being returned. Am I missing a part of the needed setup for your component? The other component is returning an alert but this one is not. Please let me know if I am missing a piece of the setup for your component. Is there something I can do that could provide you with more information on why it's not returning the alert?

**Comment by ludeeus** [comment]
And what state and zone are you using with the other one?

**Comment by Photo64** [comment]
For the other setup I have:
```
 - platform: nws_alerts
    zone_id: 'NJC035,NJZ010'
```

**Comment by Photo64** [comment]
I just received an alert on my Dev setup but again not on this component. I would expect to receive the same notification and I am stumped as to why it's not appearing based on the setup instructions for this component.

**This is what shows in my Dev setup:**

![windalert](https://user-images.githubusercontent.com/18359302/71930115-01381080-3169-11ea-95be-6efdb9473715.png)


**This is what shows with this component:**
![somerset2](https://user-images.githubusercontent.com/18359302/71930097-f67d7b80-3168-11ea-82f7-848d1ee17a5d.png)

**Comment by cjramseyer** [comment]
I would like to add, that I am using this addon installed via HACS.  I can see that there is an alert, for my configured zone.  But the only way to view the alert detail is to pull up the sensor in states under developer tools.  I should be able to view the alert by clicking the object in the HA frontend.  I get the same "alerts: [object:object]"
I would appreciate some guidance as well.

**Comment by jlverhagen** [comment]
Photo64,

I ran into the same problem and traced the issue to a problem with the weather.gov web site. It appears the Zone ID feeds (my Zone ID is WIZ038) don't always get updated or don't always get all of the alerts that are active for an area. The County ID feeds (my County ID is WIC087) do appear to have all active alerts, but the weatheralerts component is only pulling alerts from the Zone ID feeds. I issued a pull request to ludeeus with a fix that is working for me. Hopefully it will help get the component working better for everyone, as I suspect many people don't realize it isn't working since this issue doesn't generate an error because weather.gov is just returning a valid empty feed. I also have plans to add some additional functionality to allow for multiple Zone/County IDs with de-duplication and sorting of alerts.

**Comment by jlverhagen** [comment]
cjramseyer,

Check this post: https://community.home-assistant.io/t/how-to-extract-json-value-from-sensor-state-attributes/88539/2

The post isn't about the weatheralerts component, but the technique for extracting json data is the same. Hopefully that will give you the general idea of how to extract the data from the weatheralerts sensor. You would create template sensors to extract the data from the alerts object. Something like this:

{{ state_attr('sensor._youralertssensor_', 'alerts')[0]["area"] }}

would parse out the 'area' data of the first alert.

**Comment by Photo64** [comment]
jlverhagen,

I saw your pull request and was hopeful that it may correct my issue as well. Would I be able to apply you code change now and try it out? Problem being I would need an alert to occur before I would know if it worked or not.  
I assume I would have to change my sensor setup to something like this:
```
- platform: weatheralerts
  state: NJ
  zone: "C035"    <- my county code
```

**Comment by jlverhagen** [comment]
Photo65, yes, you shouldn't have any problems trying out the code changes. The _zone_ line in the config file would need the full county code **"NJC035"** and, based on that county code, in Home Assistant I believe you'll find the sensor named sensor.weatheralerts_njc035.

Alternatively, if you want to do the bare minimum of changes, you could change line 46 of custom_components/weatheralerts/sensor.py from this (changing the Z to a C):

`zoneid = f"{state}Z{zone}"`

to this:

`zoneid = f"{state}C{zone}"`

And then your config file would have:

`  zone: 35`

I was originally going to go that route, but then marine warnings for coastal waters won't work since they are all Z zone IDs.

**Comment by Photo64** [comment]
jlverhagen,
I've updated my file with all of your changes. Now just have to wait for an alert to trigger to see what gets returned. I'll provide an update once it does.

**Comment by Photo64** [comment]
jlverhagen,

So bad news, I finally got an alert from my DEV setup but even after adding your code changes I am not seeing anything in this component. This is what the sensor is now showing. After applying your code changes the sensor is now called snsor.somerset_county. Not sure where to go with this now as nothing seems to be working for this component.

![sensorSC](https://user-images.githubusercontent.com/18359302/72212449-7299fb00-34aa-11ea-9116-c6806c262505.png)

**Comment by jlverhagen** [comment]
Photo64, for details on accessing the actual alert text information, check my comment above addressed to cjramseyer. 

The State column showing 1 means the weatheralerts component has picked up one alert, and the _alerts: [object Object]_ is the alert you are looking for, but you'll need to create a template sensor to extract the alert details from the Object to display it in the HA UI. If you click on the _sensor.somerset_county_ link on the States page from your screenshot and then scroll up to the top of the States page, you should see the full alert Object text included in the States Attributes text box.

The next time I have an active alert I'll work on creating a set of template sensors and automations and post them here. Some examples of these should really have been included in the component documentation.

**Comment by Photo64** [comment]
Ah, that is helpful to know. I do see it now, I'll look into the info above on extracting the data. Looks like your code changes are working. Thanks!

![somerset4](https://user-images.githubusercontent.com/18359302/72213852-088e4f80-34c4-11ea-96e9-9353fa60c1ba.png)

**Comment by Photo64** [comment]
@jlverhagen 

So I received another weather alert in my DEV setup last night however I did not see it in this component with your coding updates. What I am not sure of is since it trigger a few hours ago does the sensor get cleared again at some point and any data that was there is gone or did it just not get triggered in this component?  The filter states is showing 0 so there is no data to capture. I did create a series of sensors to extract the data similar to this -> "{{ state_attr('sensor.somerset_county','alerts') [0] ['area'] }}"  and I was expecting that even if the initial sensor.somerset_county had been cleared away that my created sensors to capture the data would have kept it although as I write this I guess it's possible they too would have been re-written if the initial sensor was cleared out.  If it is being cleared out how would I go about capturing the data for future use? If it's not being cleared out then I guess it wasn't triggered with your code updates ??

**Comment by Photo64** [comment]
@jlverhagen 

I was able to extract data from my sensor.somerset_county on a recent alert except for 2 of the attributes, area and description. I believe it to be due to a 255 character limit. The sensors just show "unknown". All the other extracted data is captured accurately. Assuming the 255 character limit is the issue would you know how to get around being able to capture the data?

![somerset5](https://user-images.githubusercontent.com/18359302/72546183-4f7b9c80-3858-11ea-85e4-4548d540eed3.png)

**Comment by jlverhagen** [comment]
Looks like it's back to the drawing board. There is an active advisory for my area an it's not showing up in either the zone or county feed alert api endpoints. I'll work on another solution.

**Comment by Photo64** [comment]
Just out of curiosity if you're not seeing in the zone or county where are you seeing that there is an active advisory?

**Comment by Photo64** [comment]
I also didn't get a notification for an alert in my area so I downloaded your sensor.py file and overwrote what I had however after restarting HA I got this error in the log -> "Compiled zone ID 'NJZNJC035' is not valid"  Should  my sensor zone setup only include the "035" and not the full NJC035?

**Comment by jlverhagen** [comment]
I saw my missing alerts on TV, on the wunderground.com web site, and even the Atom feeds on the alerts.weather.gov site. But the api.weather.gov feeds were not updated until later in the morning. That means both the weatheralerts and the nws_alerts custom components had no alerts when there was really was an active alert.

Sorry, if you downloaded my sensor.py from my forked version using the link I posted in issue #30, I linked to the wrong file. The correct link is: 

https://github.com/jlverhagen/weatheralerts/blob/patch-1/custom_components/weatheralerts/sensor.py

I also just fixed a small issue for backward compatibility and added some additional alert data that is available with the json alert feeds.

Unfortunately, there doesn't appear to be a really good alert feed to pull alerts from. The alerts.weather.gov Atom feeds appear to be the most reliable in terms of update frequency and web server reliability, but they have truncated alert descriptions and don't have the full set of alert data that is available from the api.weather.gov feeds. The api.weather.gov feeds have better data available, but they don't appear to be reliably updated in a timely fashion and the web server that serves the api has a tendency to return errors (as it has done intermittently today).

The feed URLs I've tested (replace _**[Full_County_or_Zone_ID]**_ with actual 6-character County or Zone ID):
Atom XML Feed - https://alerts.weather.gov/cap/wwaatmget.php?x=[Full_County_or_Zone_ID]&y=0
County/Zone JSON Feed - https://api.weather.gov/alerts/active?zone=[Full_County_or_Zone_ID]
County/Zone JSON Feed - https://api.weather.gov/alerts/active/zone/[Full_County_or_Zone_ID]

The two api.weather.gov JSON feeds appear to be the same, except the /active?zone= URL allows multiple zones to be queried with one request, and it does appear to filter duplicates. This can be very useful for any boaters or beach-goers near the Oceans/Gulf of Mexico/Great Lakes, to be able to have marine alerts included with the regular weather alerts.

At this point, I think the only way to make this more reliable is to poll both the Zone and County IDs of both the JSON and Atom feeds, and give preference to the alerts in the JSON feed by discarding the alerts from the Atom feed that are already in the JSON feed. Then it will be a matter of sorting the all of the combined alerts based on when they were issued, and then finding some way to deal with the lack of data in the Atom feeds.

I'm not sure when I'll get these ideas implemented. I'll first work on posting some template sensor configurations and possibly some automations this weekend, since I'll have some alerts to work with for the next 20+ hours.

**Comment by Photo64** [comment]
I just updated my sensor.py with your latest update now I'll have to wait and see for the next alert. I was working on some template sensors and trying to trigger a persistent_notification but it's hard to test until an alert actually gets triggered. Looking forward to seeing your examples on this.

**Comment by jlverhagen** [comment]
One more update to sensor.py available with minor tweaks and corrections:

https://github.com/jlverhagen/weatheralerts/blob/patch-1/custom_components/weatheralerts/sensor.py

And my weather_alerts.yaml package (automations/script sections not fully tested yet):

https://github.com/jlverhagen/weatheralerts/blob/patch-1/weather_alerts.yaml

To use the yaml package as-is you will need to rename your weatheralerts sensor Entity ID to sensor.weatheralerts_1 or do a search-and-replace on the yaml package and replace all occurrences of sensor.weatheralerts_1 with your weatheralerts sensor Entity ID (sensor.somerset_county), change the zone: and state: lines accordingly, and remove any existing weatheralerts yaml configuration you have in any other yaml files.

**Comment by Photo64** [comment]
Your weather_alerts.yaml package is very impressive, far more than what I was trying to put together. I copied the raw data into a new weather_alerts.yaml file however I am getting a number of errors that I can't seemed to get past. Mostly "bad indentation" however I tried various things and still get the error. I realized you said you haven't tested this yet but are you able to load this HA without hitting errors?

This is what I get from the "Check Config"
Error loading /config/configuration.yaml: while parsing a block collection
  in "/config/packages/weather_alerts.yaml", line 467, column 7
expected <block end>, but found '?'
  in "/config/packages/weather_alerts.yaml", line 497, column 7

This is what I see in VS Code:
![bad_indentation](https://user-images.githubusercontent.com/18359302/72686720-9b7f4900-3ac5-11ea-87e3-3ce54521f916.png)

**Comment by Photo64** [comment]
Your weather_alerts.yaml package is very impressive, far more than what I was trying to put together. I copied the raw data into a new weather_alerts.yaml file however I am getting a number of errors that I can't seemed to get past. Mostly "bad indentation" however I tried various things and still get the error. I realized you said you haven't tested this yet but are you able to load this HA without hitting errors?

This is what I get from the "Check Config"
Error loading /config/configuration.yaml: while parsing a block collection
  in "/config/packages/weather_alerts.yaml", line 467, column 7
expected <block end>, but found '?'
  in "/config/packages/weather_alerts.yaml", line 497, column 7

This is what I see in VS Code:
![bad_indentation](https://user-images.githubusercontent.com/18359302/72686720-9b7f4900-3ac5-11ea-87e3-3ce54521f916.png)

**Comment by jlverhagen** [comment]
I really messed up the yaml when copying and pasting some edits. A large chunk of the yaml was partially duplicated instead of being replaced. It should be correct now:

https://github.com/jlverhagen/weatheralerts/blob/patch-1/weather_alerts.yaml

The only issue I see right now with the yaml is the template sensor attributes will throw an error when Home Assistant starts up if there isn't an active alert for the sensor. I'm using yaml code like this: 

{{ states.sensor.weatheralerts_1.attributes.alerts[0].event }}

and similar format to get the alert data from the alerts[] object. Using state_attr like this:

{{ state_attr('sensor.weatheralerts_1', 'alerts[0].event') }} 

is what should be used to prevent the startup errors, but having 'alerts[0].event' as the attribute doesn't seem to work or isn't the correct syntax for dealing with objects. If I can't figure out a state_attr way of filling the attributes, then I'll add if/else checks around the attributes so they don't throw dozens of errors on every restart.

**Comment by jlverhagen** [comment]
hmmm. I just tried the state_attr format again and didn't get an error this time in the Developer Tools Template renderer. I'll try to get the yaml updated with the state_attr format in the template sensors, tested, and uploaded sometime later tonight.

**Comment by Photo64** [comment]
@jlverhagen 

Saw that you reposted your code. Downloaded the updated code and it looks good now. Need to wait for the next alert to try this out - thx

**Comment by jlverhagen** [comment]
After some alerts came up overnight last night and during the day while I was at work, I can see the persistent notification in my posted yaml configuration is triggering but it is displaying None for the notification title and message text. I suspect it has something to do with using state_attr in the alerts template sensor attributes because it was displaying the correct title and message before making that change. I'll investigate it further...

**Comment by jlverhagen** [comment]
After my recent updates to https://github.com/jlverhagen/weatheralerts/blob/patch-1/weather_alerts.yaml everything seems to be functioning correctly and as-expected when a single alert is active. I still have to test the Pushbullet automation, add the ability to display multiple alerts via UI Notifications when multiple alerts are active, and test the overall handling of multiple alerts. I also added another automation to auto-dismiss the UI notification after 30 minutes of not having any active alerts (I'll probably add an input sensor to allow the auto-dismiss timeout to be changed).

Since this is getting more off the topic of the initial issue here, I'll post further yaml discussion in the pull request comments, and possibly start a message thread on the home-assistant.io message board.

**Comment by Photo64** [comment]
I just updated with your recent change however I am not sure if I am getting the alerts properly. I again received an alert on my Dev setup but did not see this alert triggered. If this alert is set back to no active alerts I assume my sensor will show nothing??  If this is true I may have missed it unlike my Dev sensor which seems to hold the information within the persistent notification. I have to wait again I receive an alert unless there is a way you are aware of that I can test this, maybe use a zone that has an active alert?

**Comment by jlverhagen** [comment]
If you are using the yaml I just posted today, I did add an auto-dismiss automation in there that will dismiss the persistent UI notification 30 minutes after the active alert count returns to 0. In your Home Assistant web interface, go to the Configuration page, then to the Automation page (the Automation Editor), and look for the Weather Alert UI Notification and Weather Alert UI Notification Auto-dismiss automations. The last triggered time of the Weather Alert UI Notification automation will tell you when a UI notification should have been set, and the last triggered time of the Weather Alert UI Notification Auto-dismiss automation will tell you when that UI notification should have been dismissed. From the Automations Editor, if you disable the Weather Alert UI Notification Auto-dismiss automation, the persistent notification should remain until you manually dismiss it. 

That is correct about the sensor showing nothing... if the alerts json feed has no alerts, the sensors will no longer contain the alert data. But the state history of the weatheralerts sensors should give you an indication if something (or nothing) has occurred. The only way I know to test it is to pick another county ID that does have an active alert, set that ID in the yaml, then restart Home Assistant. Then, almost immediately after your browser reconnects with Home Assistant, a persistent UI notification should show up.

You can check the state history in the Developer Tools States tab, clicking the Info icon to the left of the sensor.weatheralerts_1 entity to check the graph to confirm when and how many alerts have been active through the weatheralerts component. If you don't see indications of alerts there, I'm at a loss to explain it, except for a potential issue if the alert feed doesn't contain all of the data I've set the component to use. In this case, I believe you would see some sort of weatheralerts error in the Home Assistant log file. I think I'll add some sanity checks to that part of the sensor.py code just to be safe. If you do see indications of alerts in the state history but the automation last triggered time doesn't correspond to an alert, I'd suspect you may have made some changes to the sensors or automations that is preventing the Weather Alert UI Notification from properly triggering.

**Comment by Photo64** [comment]
I just updated to your latest code just a little earlier today so it would have been after the latest alert that I saw in my Dev environment. I'll look for an active zone area and try using that with a restart to see what happens. I may also look at adjusting that 30 minutes to a longer period. Thanks for all your doing on this.

**Comment by Photo64** [comment]
As luck would have it I received an alert overnight however it didn't pull any information and my persistant notification appears blank. I pasted some screenshots below. I updated to your latest changes and you can see that the sensor.somerset_county didpull some information however the sensor you created "sensor.weatheralerts_alert_1" shows as 'on' but all the attributes show as none. I did replace all the templates with "sensor.somerset_county". Did I possibly update something incorrectly? Why would the attributes be showing with 'none'?

1st screenshot - persistent notification
2nd screenshot - sensor.somerset_county
3rd screenshot - attributes of sensor.weatheralerts_alert_1

![Non_Notification](https://user-images.githubusercontent.com/18359302/73135744-d7f5fc00-4013-11ea-8dae-99ada1a90bdf.png)
![sensor_soerset_county](https://user-images.githubusercontent.com/18359302/73135745-e04e3700-4013-11ea-8200-95d719d0cc90.png)
![sesnor_weatheralert_1](https://user-images.githubusercontent.com/18359302/73135746-e2b09100-4013-11ea-8039-5ad3da865ac7.png)

**Comment by Photo64** [comment]
As luck would have it I received an alert overnight. At first it didn't appear to be working however I had forgotten to restart HA. Once I did I was able to see the persistent notification appear correctly. A screenshot is below.

![weatheralerts_alert_1](https://user-images.githubusercontent.com/18359302/73135956-7be0a700-4016-11ea-9f78-61614d1e55bd.png)

**Comment by jlverhagen** [comment]
Nice.

I forgot to mention... if you do change the county or zone ID, then you would also have to make the appropriate changes to the template sensors (changing sensor.weatheralerts_1 or sensor.somerset_county to the newly created sensor entity for the new ID) in the yaml if you opted to update the yaml sensors with your default weatheralerts sensor entity ID. Or, if keeping the yaml sensors as-is (keeping sensor.weatheralerts_1), you would need to go to Configuration, then Entities, and remove the old entity that was assigned to sensor.weatheralerts_1 and then find the new entity for new county or zone ID entity and change the Entity ID of that entity to sensor.weatheralerts_1.

**Comment by Photo64** [comment]
@jlverhagen 
It seems you have been making some updates and I am trying to follow them. Looks like you updated the sensor.py file and made changes to the weatheralerts.yaml file. It also looks like you added a second weather_alerts_2.yaml file. Is the purpose of this second yaml file in case the first one doesn't capture the alert?

**Comment by Photo64** [comment]
@jlverhagen
I updated to your latest 2 yaml files and sensor.py file however I am receiving an error on checking config.  Looks like it doesn't like the "type:" variable?

Invalid config for [sensor.weatheralerts]: [type] is an invalid option for [sensor.weatheralerts]. Check: sensor.weatheralerts->type. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/weatheralerts/
Invalid config for [sensor.weatheralerts]: [type] is an invalid option for [sensor.weatheralerts]. Check: sensor.weatheralerts->type. (See ?, line ?). Please check the docs at https://home-assistant.io/integrations/weatheralerts/

**Comment by jlverhagen** [comment]
I'll provide a more detailed response when I get home from work, but check
the the commit comments for my sensor.py and yaml for clues to what I've
done.

**Comment by jlverhagen** [comment]
For the most recent sensor.py, I have taken the suggestions and requirements that ludeeus specified in the pull request comments and implemented them. I don't agree with all of the suggestions and requirements, but I'll make those counterpoints in the pull request comments. This most recent sensor.py includes reverting the changes I made to allow multiple zone/county IDs and allowing full 6-character zone/county IDs to be used for the **zone** config option in the weatheralerts platform yaml config. This means the zone ID should now be specified as a number only for the **zone** config option, and a new config option named **type** should be set to either _county_ or _zone_ to indicate whether the **zone** ID number represents the geographical zone ID (xxZ###) or the county ID (xxC###).

With the most recent sensor.py, your platform config should look like this:
```
- platform: weatheralerts
  state: NJ
  zone: 35
  type: county
```

For the yaml, the weather_alerts_2.yaml should only be used for a second weatheralerts zone ID. If you only monitor one zone or county ID, then you should delete weather_alerts_2.yaml. In the weather_alerts.yaml, I changed the alert sensor names from weatheralerts_alert_# format to weatheralerts_#_alert_# format so multiple platform configurations can be used with consistent sensor naming across multiple alert zones. Also, the naming of the automations and script were similarly changed so they can be used in multiple yaml packages if needed. There were a couple of small corrections to the yaml and I added sensors to attempt to track previous alerts (not fully working yet). I also added some documentation to the top of the yaml packages.

**Comment by Photo64** [comment]
I received an alert for my area and it created the persistent_notification with all the information included. It appears to be working now as expected. Again thanks for all your work on this.
