### ISSUE TITLE
Only one alert showing up

### ISSUE THREAD

**Issue by ntilley905** [custom-components/weatheralerts#30]
The other day my county had multiple alerts at once (I believe we only got to two), a wind advisory and a tornado watch. However, the component only ever picked up the wind advisory (I assume because it was published first). Is this a limitation of the component or something that could potentially be fixed, or am I doing something wrong?

Config:
```
- platform: weatheralerts
  state: 'GA'
  zone: '033'
```

**Comment by jlverhagen** [comment]
Check the pull request I submitted (https://github.com/custom-components/weatheralerts/pull/29). The problem is the weatheralerts component is only using zone ID alert feeds. And the weather.gov website doesn't appear to be keeping those feeds accurately updated. The county ID alert feeds do appear to be accurately updated. The pull request I submitted adds the ability to use county IDs. Read my comment on the pull request page. The comment gives some instructions and details.

You can either manually apply the changes from the pull request or download my updated version of the sensor.py file from my weatheralerts fork here: https://github.com/jlverhagen/weatheralerts/blob/master/custom_components/weatheralerts/sensor.py

**Comment by jlverhagen** [comment]
Sorry, in my reply above I linked to the master sensor.py instead of the patched version. The link is updated to the correct patched sensor.py file.
